### ISSUE TITLE
State of 1.0.0 release

### ISSUE THREAD

**Issue by kindrowboat** [ceylinkeylan/mu-wizard#15]
Hello, first off, thank you so much for this package. It made it very easy for me to get up-and-running with mu4e, and I still install it on new systems to "sanity test" the setup.

I'm interested in packaging this for nixos. Unlike, say, AUR, nixos packages must be tied to either a specific (tagged) version or commit. I noticed that you posted 1.0.0-rc1 about a year ago, but there have been quite a few commits since then. Are you planning to cut a 1.0.0 anytime soon?

**Comment by cemkeylan** [comment]
Hello, thank you for your kind words. The only things left to do for the release is completing the documentation. I'll tag the `1.0.0-rc2` and make the release in a couple of days

**Comment by cemkeylan** [comment]
Alright, turns out there was nothing much left to be done in terms of documentation. I've tagged the first release.
